### ISSUE TITLE
Auxiliary Classifier

### ISSUE THREAD

**Issue by ssakhavi** [nagadomi/kaggle-cifar10-torch7#2]
Hi,

From your code, I couldn't find out where you have implemented the auxiliary classifier. 

Can you please elaborate?

**Comment by nagadomi** [comment]
Hi,

What does "auxiliary classifier" mean?
Definition of classifier can be found at `./very_deep_model.lua`.

**Comment by ssakhavi** [comment]
In the Inception architecture, there are two auxiliary classifiers to
support back propagation. In your code for inception, I couldn't find it.

**Comment by nagadomi** [comment]
I did not use Inception architecture for this competition.
`inception_model.lua` is only 3a-4c layers of inception module. It is not a correct implementation.
And this model gives me score of 0.88 on CIFAR-10.
If you need Inception architecture, refer to nicholas-leonard's implementation.
https://github.com/nicholas-leonard/dp/issues/82

Sorry for the confusion.
